### ISSUE TITLE
Add list of datasets and instruments

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/dashboard#18]
Is it possible to add a list of all instruments and a list of all datasets in Discovery?

**Comment by ollylucl** [comment]
It should be possible to add these but I need a bit more info: where would you get the info about datasets and instruments? If I click on a link to a sweep in the dashboard application (e.g. https://discovery.closer.ac.uk/item/uk.cls.nextsteps/7d451bc1-8462-48c4-a380-755d95b5d0d4) I can see that there are tabs called 'Data' and 'Questionnaires' which seem to hold information about datasets and instruments?

Also, once this information is obtained from the API, where should it be displayed in the dashboard UI?

**Comment by ollylucl** [comment]
Is the 'Mode of Collection' tab on the dashboard application not a list of all the instruments in Discovery?

**Comment by HayleyMills** [comment]
For the example you linked the mode of collections are highlighted and the instrument name (prefix) and name (title) are underlined which is what the list would be of. 
![image](https://github.com/CLOSER-Cohorts/dashboard/assets/16664703/df1c4a01-b9d1-4c16-8194-39d3c004a56b)

**Comment by ollylucl** [comment]
So are you requesting two extra tabs/screens to be added to Dashboard: 

one showing all the unique instruments (i.e. the concatenated values of 'Name' and 'Label' fields from the screenshot above)
one showing all the unique datasets (which are found in the 'Data' tab on sweep pages such as the page I've linked to)

**Comment by HayleyMills** [comment]
So having spoken to JJ, we think it might be better to have a second dashboard which focusses on checks for content updates including the list of; instruments (name and label. Note that the name is unique.), datasets (title alternative title), orphans, deprecations etc. JJ will discuss and we can create a new wiki page with the details.
