### ISSUE TITLE
Add Data Collection Organisation check

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/dashboard#73]
All Data Collections should have a Data Collection Organisation, could you display any where this is not the case

**Comment by ollylucl** [comment]
Fyi, the counts for dataCollection according to https://discovery.closer.ac.uk/api/v1/repository/statistics and https://clsr-ppcolw01n.addev.ucl.ac.uk/api/v1/repository/statistics don't match. On live, the values for DataCollection in ItemCounts and ItemRevisionCounts are both 481, but on the staging environment the number of DataCollection items reported in ItemCounts is 506, and in ItemRevisionCounts it's 541. Just thought I'd flag it up, not sure if it's an issue.

**Comment by ollylucl** [comment]
What do you mean by 'Data Collection Organisation'? Is that an Organisation item (as defined at https://docs.colectica.com/introduction/information-model/complete/?highlight=organization%20item) that references a DataCollection item?

**Comment by spuddybike** [comment]
I’ve updated content on staging so it will. E different On 13 May 2024, at 12:01, ollylucl ***@***.***> wrote:﻿
Fyi, the counts for dataCollection according to https://discovery.closer.ac.uk/api/v1/repository/statistics and https://clsr-ppcolw01n.addev.ucl.ac.uk/api/v1/repository/statistics don't match. On live, the values for DataCollection in ItemCounts and ItemRevisionCounts are both 481, but on the staging environment the number of DataCollection items reported in ItemCounts is 506, and in ItemRevisionCounts it's 541. Just thought I'd flag it up, not sure if it's an issue.
